### ISSUE TITLE
Write README file

### ISSUE THREAD

**Issue by SalmaIssa96** [GSG-CF04/To-Do-list-team3#1]
README file contains :

- [x]  Project name
- [x] Project description
- [x]  user stories
- [x]  Live link [github pages]
- [x] How do I get the project on my local machine?
- [x]  team members

**Comment by techhana2014** [comment]
# To-Do list App
#### "To-Do List" are prioritized lists of all the tasks that you need to carry out. They list everything that you have to do, with the most important tasks at the top of the list, and the least important tasks at the bottom.


## Prerequisite Knowledge
#### Basics of HTML, CSS and JS (specially DOM Manipulations)

### 1- Make a simple sketch of To-do app which contains all your decided features:
- Add task to list
- Remove Completed task
- Edit to task
- Dark theme
- Responsive Desgin

### 2- Prototype:
- Make a color palette
- Choose the typeface.
- Collect SVG icons
- Start designing
- Design the Dark theme

### 3- Setup Project Environment:
#### In this step, setup the directories and create files for your project.

### 4-  Create HTML structure
### 5- Add CSS Styling
### 6- Add JavaScript Functionality

## Live link

https://gsg-cf04.github.io/To-Do-list-team3/

## How do I get the project on my local machine?

### First you need to visit this [link](https://github.com/GSG-CF04/To-Do-list-team3) and follow these steps:

#### 1. Copy the the link of the code from the main branch. 
#### 2. Run GitBash in the folder that you want to run the project at.
#### 3. Use the command `Git clone (the link you copied)`
#### 4. After getting the files localy,you will enter the folder of the project using the `cd To-Do-list-team3` command.
#### 5. To open the proejct files with your code editor,you insert the command `code .`.
#### 6. Use Live server to run the project locally.
## Team members:
- Fady ALwazir
- salma yossef issa 
- Israa Hamdi Abu Rayya
- Hana Hijazi
## Design :
![](https://i.imgur.com/RAMIcK7.png)
## final design :point_down:
-Desktop Design
![](https://i.imgur.com/HKdi6Sh.png)

-Mobile Design
![](https://i.imgur.com/ayelyPU.png)

-Dark Mode
![](https://i.imgur.com/pw11hxm.png)

**Comment by techhana2014** [comment]
Hello everyone, please review the text for approval
